openapi: '3.0.3'
info:
  title: API Title
  version: '1.0'
servers:
  - url: http://localhost:5000
paths:
  /user/like-product:
    post:
      parameters:
        - in: path
          name: user
          schema:
            type: string
          required: true
          description: Numeric ID of the user
        - in: path
          name: product
          schema:
            type: string
          required: true
          description: Numeric ID of the product
      responses:
        '200':
          description: OK

      
